[package]
name = "polyominoSolver"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
serde = "1.0"



[lib]
name = "polyominoSolver"
path = "src/main.rs"

# crate-type = ["cdylib", "rlib"]

[[bin]]
name = "polyominoSolver"
path = "src/main.rs"
